# 'numpy'

- numpy has been optimized for processing

In [1]:
# import Numpy with standard abbreviation

import numpy as np

# Variables
- a name we assign to an object in Python

In [2]:
# assign a small array to a variable a

a = np.array([[1,1,2], [3,5,8]])

We can see the variable's value in 2 ways:

In [3]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## naming variables

in the class, we are going to use 'snake_case' for naming variables.

# Variables and objects

**object**: often encountered in Python documentation and tutorials.
object is a bundle of properties and actions about something specific

Example:

- object: data frame
- properties: number of rows, names of columns, data created
- actions: selecting a row, adding a column

A variable is a name we give a specific object, and the same object can be referenced by different variables.

Example:

- The Sun(actual star at the center of the solar system) = object
- sol = Spanish word for Sun = variable
- soleil = Fren for Sun = another variable

In practice: we will use object and variable interchangeably



# Types

Each object in Python has a type.

type = what kind of object it is

We can also call the type of the object, the **class** of the object.

We can see the type/class of an object by using the type function

In [5]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The 'numpy.ndarray' is the core object/data type in the NumPy package

we can check the type of an entry in the array by indexing:

In [7]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

In [8]:
# how would you access the value 5 in the array a?

In [9]:
print(a[1,1])

5


# Functions

'print' was our first example of a Python function:
    
A function:
- take in a set of **arguments**, separated by commas, and
- use those arguments to produce some **output**

argument = parameter : you might see argument more often in doc.

We can ask info by executing ? followed by function name

In [11]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- first line: function showing all of its arguments in parenthesis
- then a short description of what the function does
- finally, a list of the arguments and a brief expl. of each of them.

Different types of arguments inside the parenthesis. Roughly speaking, there are 2 types of arguments:

- **non-optional arguments**: arguments you need to specify for the function to do something
- **optional arguments**: arguments that are pre-filled with a default value by the function, but we can override them. Optional arguments appear inside the parenthesis.

In [12]:
print('changing the default end argument of the print function', end=':)')

changing the default end argument of the print function:)

# Atributes and Methods

An object in Python has attributes and methods

**attribute**: property of an object (some can be changed and others cannot)
**method**: procedure associated with an object

Access a variable's attributes and methods by adding a period'.' at the end of the variable's name

'variable.variable_method()'
or
'variable.variable_attribute()

Examples:

Methods and attributes of NumPy arrays:


In [1]:
import numpy as np

In [4]:
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
var.shape

(3, 3)

In [6]:
type(var.shape)

tuple

In [7]:
# ndim is an attribute holding the number of array dim.

var.ndim

2

In [8]:
type(var.ndim)

int

- Notice attributes can have many different data types.

Examples of methods:

In [9]:
# min method for array
# return the min value in the array

var.min()

1

In [10]:
type(var.min)

builtin_function_or_method

In [ ]:
# R and Python

R:
- doesn't use methods within an object
- functions in R are extrinsic to (outside) the objects they are acting on

Ex: recreate getting the min value in an array

In R there would be 2 separate items: the variable 'var' and a separate function 'min' that gets 'var' as a parameter

# this is R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
min(var)

Using the pipe operator >%> in R's tidyverse is closer to the '.' in Python

var <- array(c(1,4,7,2,5,8,3,6,9), dim=c(3,3))
var >%> min()

What is happening?
The pipe >%> is passing 'var' to the 'min()' function as its first argument. This is what '.' does in Python.
var.min()